// EXERCISE:
// You can write all the code natively (for cycles and such) or you can use some advanced functions which JS arrays provides in case you see them fit
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
// There can be multiple solutions to each task, solve it as you see fit.
// You will work with array `numbers` which will be generated by code (code below) in every task.
// Write these functions:

// This block generates array with random length with values between 1-100
let numbers = [];
const length = Math.ceil(Math.random() * 10) + 5;
for (let i = 0; i < length; i = i + 1) {
  numbers.push(Math.ceil(Math.random() * 100));
}

// a) Function which will print to console a whole array
/** @param numbers {any[]} */
const printArray = (numbers) => {
  // Your code:
  console.log(numbers);
};

// b) Function which will print to console the length of array
/** @param numbers {any[]} */
const printLength = (numbers) => {
  // Your code:
  console.log(numbers.length);
};

// c) Function which will print to console the first element of array
/** @param numbers {any[]} */
const printFirstItem = (numbers) => {
  // Your code:
  console.log(numbers[0]);
};

// d) Function which will print to console the last element
/** @param numbers {any[]} */
const printLastItem = (numbers) => {
  // Your code:
  console.log(numbers[numbers.length - 1]);
};

// e) Function which will print to console the largest number (You can check Math functions)
/** @param numbers {any[]} */
const printLargestItem = (numbers) => {
  // Your code:
  console.log(Math.max(...numbers));
};

// f) Function which will print to console the smallest number (You can check Math functions)
/** @param numbers {any[]} */
const printSmallestItem = (numbers) => {
  // Your code:
  console.log(Math.min(...numbers));
};

// g) Function which will print to console the sum of all numbers in array (You can check reduce function)
/** @param numbers {any[]} */
const printSum = (numbers) => {
  // Your code:
  console.log(numbers.reduce((x, y) => {return x + y}, 0));
};

// h) Function which will print to console the difference between the largest and the smallest number (You can check Math functions)
/** @param numbers {any[]} */
const printSALDifference = (numbers) => {
  // Your code:
  console.log(Math.max(...numbers) - Math.min(...numbers));
};

// i) Function which will print to console the average of all numbers (You can check reduce function)
/** @param numbers {any[]} */
const printAverage = (numbers) => {
  // Your code:
  console.log(Math.av(...numbers) - Math.min(...numbers));
};

// j) Function which will print to console the index of largest number (You can check Math functions)
/** @param numbers {any[]} */
const printLargestsIndex = (numbers) => {
  // Your code:
    console.log((numbers.length > 0) ? (numbers.reduce((x, y) => {return x + y}, 0)/numbers.length) : (0));
};

// k) Function which will print to console the even numbers (not the array of even numbers),
// if array doesn't contain any even number, show text "Even number isn't in array"
/** @param numbers {any[]} */
const printEvenNums = (numbers) => {
  // Your code:
  numbers.forEach((value) => {
    if(~value & 1)
      console.log(value);
  });
};

// l) Function which will multiple by 2 every number in array and print the array to console
// Example: printNumsMultipliedBy2([1,2,3]) -> [2,4,6]
/** @param numbers {any[]} */
const printNumsMultipliedBy2 = (numbers) => {
  // Your code:
  console.log(numbers.map(x => x * 2))
};
